"""
Build script — generates src/assets/resources_rc.py from the icons in src/assets/icons/.
Run from the project root:
    python scripts/build_resources.py
Re-run whenever icons are added or changed.
"""
import base64
import os

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
ASSETS_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "assets")
OUTPUT_FILE = os.path.join(ASSETS_DIR, "resources_rc.py")

ICONS = {
    ":/icons/IMG-Close.png":      os.path.join(ASSETS_DIR, "icons", "IMG-Close.png"),
    ":/icons/IMG-Members.png":    os.path.join(ASSETS_DIR, "icons", "IMG-Members.png"),
    ":/icons/IMG-Attendence.png": os.path.join(ASSETS_DIR, "icons", "IMG-Attendence.png"),
    ":/icons/IMG-Pyments.png":    os.path.join(ASSETS_DIR, "icons", "IMG-Pyments.png"),
}

# ---------------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------------
lines = [
    "# Auto-generated by scripts/build_resources.py — do not edit manually.",
    "# Re-run:  python scripts/build_resources.py",
    "",
    "from PyQt6.QtCore import QByteArray",
    "from PyQt6.QtGui import QPixmap, QIcon",
    "import base64",
    "",
    "_resources: dict[str, str] = {}",
    "",
]

for resource_path, file_path in ICONS.items():
    with open(file_path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("ascii")

    # Split into 80-char chunks so the file stays readable
    chunks = [encoded[i:i + 80] for i in range(0, len(encoded), 80)]
    joined = '"\n    "'.join(chunks)

    lines.append(f'_resources["{resource_path}"] = (')
    lines.append(f'    "{joined}"')
    lines.append(")")
    lines.append("")

lines += [
    "",
    "def get_icon(path: str) -> QIcon:",
    '    """Returns a QIcon for the given resource path, e.g. :/icons/IMG-Close.png"""',
    "    data = _resources.get(path)",
    "    if data is None:",
    "        return QIcon()",
    "    raw = base64.b64decode(data)",
    "    ba = QByteArray(raw)",
    "    pixmap = QPixmap()",
    "    pixmap.loadFromData(ba)",
    "    return QIcon(pixmap)",
]

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated: {OUTPUT_FILE}")
for rp in ICONS:
    print(f"  {rp}")
